#!/usr/bin/env bash
set -euo pipefail

# Run on your own computer with an authenticated GitHub CLI. Never commit the
# generated keystore: it is the identity used for every future Feist debug APK.
repo="BirdMachine/Feist"
signing_dir="${XDG_DATA_HOME:-$HOME/.local/share}/feist-signing"
keystore="$signing_dir/feist-debug.keystore"
credentials="$signing_dir/credentials.env"
alias_name="feist-debug"

command -v gh >/dev/null || { echo 'Install GitHub CLI (gh) first.' >&2; exit 1; }
command -v keytool >/dev/null || { echo 'A JDK with keytool is required.' >&2; exit 1; }
command -v openssl >/dev/null || { echo 'OpenSSL is required.' >&2; exit 1; }
gh auth status >/dev/null || { echo 'Run gh auth login first.' >&2; exit 1; }

umask 077
mkdir -p "$signing_dir"
if [[ -e "$keystore" && ! -e "$credentials" || ! -e "$keystore" && -e "$credentials" ]]; then
  echo "Incomplete signing identity in $signing_dir; restore both files from backup." >&2
  exit 1
fi
if [[ ! -e "$keystore" ]]; then
  store_password="$(openssl rand -hex 24)"
  key_password="$store_password"
  keytool -genkeypair -noprompt -keystore "$keystore" \
    -storepass "$store_password" -keypass "$key_password" \
    -alias "$alias_name" -keyalg RSA -keysize 3072 -validity 36500 \
    -dname 'CN=Feist Debug, O=BirdMachine' >/dev/null
  printf 'FEIST_DEBUG_STORE_PASSWORD=%s\nFEIST_DEBUG_KEY_PASSWORD=%s\n' \
    "$store_password" "$key_password" > "$credentials"
  echo "Generated signing identity in $signing_dir"
fi

# credentials.env is generated by this script and contains only hex values.
source "$credentials"
base64 < "$keystore" | tr -d '\n' | gh secret set FEIST_DEBUG_KEYSTORE_B64 -R "$repo"
printf '%s' "$FEIST_DEBUG_STORE_PASSWORD" | gh secret set FEIST_DEBUG_STORE_PASSWORD -R "$repo"
printf '%s' "$alias_name" | gh secret set FEIST_DEBUG_KEY_ALIAS -R "$repo"
printf '%s' "$FEIST_DEBUG_KEY_PASSWORD" | gh secret set FEIST_DEBUG_KEY_PASSWORD -R "$repo"
echo 'Four Feist Actions signing secrets are set. Back up the keystore and credentials.env securely; losing them prevents update-in-place.'
echo 'Start a new Feist build from GitHub Actions, or push a new commit to main.'
