#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
# The bundled tiny wrapper exists only because the ChatGPT build sandbox cannot fetch
# Gradle's official wrapper JAR. Once Gradle is available, this replaces it with the
# official wrapper files generated by Gradle itself.
./gradlew wrapper --gradle-version 8.13 --distribution-type bin
printf '\nOfficial Gradle wrapper regenerated.\n'
